# Generated by Django 6.1.1 on 2026-09-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_remove_author_id_author_auth_id'),
        ('book', '0002_alter_book_upt_at_alter_book_table'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bk_desc', models.TextField()),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('upt_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='author.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book')),
                ('stdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='student.student')),
            ],
            options={
                'db_table': 'bkrv',
            },
        ),
    ]
