# Generated by Django 6.1.1 on 2026-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='auth_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
