# Generated by Django 6.1.1 on 2026-09-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_upt_at_alter_book_table'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('upt_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='book.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues', to='student.student')),
            ],
            options={
                'db_table': 'bkis',
            },
        ),
    ]
