# Generated by Django 6.1.1 on 2026-09-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_remove_author_id_author_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bk_name', models.CharField(max_length=255)),
                ('bk_desc', models.CharField(max_length=255)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('upt_at', models.DateTimeField(auto_now_add=True)),
                ('crt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
