# Generated by Django 6.1.1 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stdt_name', models.CharField(max_length=255)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('upt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Stdt',
            },
        ),
    ]
